#!/usr/bin/env python3
"""
Generate an Adafruit GFX font header (RouteBold.h) for the LED flight tracker's
route row. Uses Pillow (PIL) only -- no freetype dev headers / fontconvert needed.

Renders glyphs 0x20..0x5A (space, digits, A-Z + punctuation) from a condensed
bold TTF, byte-aligning each glyph's bitmap (matching Adafruit drawChar, which
resets its bit counter per glyph and reads from byte `bitmapOffset`, MSB first).

The font size is auto-selected: the largest size whose worst-case route
("3 widest caps" + arrow + "3 widest caps") still fits within the 64px panel.
"""
from PIL import Image, ImageDraw, ImageFont

TTF = "/usr/share/fonts/truetype/open-sans/OpenSans-CondBold.ttf"
OUT = "/home/jono/repos/led_flight_tracker/main/fonts/RouteBold.h"
NAME = "RouteBold"
FIRST, LAST = 0x20, 0x5A
PANEL_W = 64
ARROW_BUDGET = 11        # px reserved for the triangle arrow + padding
WIDTH_TARGET = 62        # leave a little margin below 64
ORIGIN = 80              # baseline origin on the scratch canvas
THRESH = 128             # AA -> 1bpp threshold

def glyph_metrics(font, ch):
    """Return (width, height, xadvance, xoff, yoff, rows[list of int rows]) for ch."""
    img = Image.new("L", (ORIGIN * 2, ORIGIN * 2), 0)
    d = ImageDraw.Draw(img)
    d.text((ORIGIN, ORIGIN), ch, fill=255, font=font, anchor="ls")  # left, baseline
    bbox = img.getbbox()
    adv = round(font.getlength(ch))
    if bbox is None:  # blank glyph (space)
        return 0, 0, adv, 0, 0, []
    l, t, r, b = bbox
    w, h = r - l, b - t
    px = img.load()
    rows = []
    for y in range(t, b):
        row = 0
        for x in range(l, r):
            row = (row << 1) | (1 if px[x, y] >= THRESH else 0)
        rows.append((row, w))
    return w, h, adv, l - ORIGIN, t - ORIGIN, rows

def avg_cap(font):
    advs = [font.getlength(chr(c)) for c in range(0x41, 0x5B)]
    return sum(advs) / len(advs)

def pick_size():
    # Largest size whose *typical* 6-letter route (avg cap width) + arrow fits.
    # Rare M/W-heavy codes that exceed 64px are handled by the runtime width
    # guard (falls back to TomThumb x2, which is a similar height).
    best = 12
    for size in range(20, 11, -1):
        font = ImageFont.truetype(TTF, size)
        typical = 6 * avg_cap(font) + ARROW_BUDGET
        if typical <= WIDTH_TARGET:
            best = size
            break
    return best

def main():
    size = pick_size()
    font = ImageFont.truetype(TTF, size)
    ascent, descent = font.getmetrics()
    yadvance = ascent + descent

    bitmaps = []        # flat list of bytes
    glyphs = []         # (offset, w, h, adv, xoff, yoff, comment)
    offset = 0
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        w, h, adv, xoff, yoff, rows = glyph_metrics(font, ch)
        gbytes = []
        bitpos = 0
        acc = 0
        for (row, rw) in rows:
            for x in range(rw):
                bit = (row >> (rw - 1 - x)) & 1
                acc = (acc << 1) | bit
                bitpos += 1
                if bitpos == 8:
                    gbytes.append(acc); acc = 0; bitpos = 0
        if bitpos:
            acc <<= (8 - bitpos)
            gbytes.append(acc)
        glyphs.append((offset, w, h, adv, xoff, yoff, ch))
        bitmaps.extend(gbytes)
        offset += len(gbytes)

    # sample widths for a log line
    def route_w(s):
        return sum(round(font.getlength(c)) for c in s)

    lines = []
    lines.append("#pragma once")
    lines.append("#include <Adafruit_GFX.h>")
    lines.append("")
    lines.append("// Open Sans Condensed Bold (Apache-2.0), rasterized at %dpx via PIL." % size)
    lines.append("// Generated by main/fonts/gen_route_font.py for the route row (3-letter")
    lines.append("// airport codes). Glyphs 0x%02X..0x%02X, byte-aligned per glyph." % (FIRST, LAST))
    lines.append("")
    # bitmaps
    lines.append("const uint8_t %sBitmaps[] PROGMEM = {" % NAME)
    row = "  "
    for i, b in enumerate(bitmaps):
        row += "0x%02X, " % b
        if (i % 12) == 11:
            lines.append(row.rstrip()); row = "  "
    if row.strip():
        lines.append(row.rstrip())
    lines.append("};")
    lines.append("")
    # glyphs
    lines.append("const GFXglyph %sGlyphs[] PROGMEM = {" % NAME)
    for (off, w, h, adv, xoff, yoff, ch) in glyphs:
        safe = ch if ch.isalnum() else ("0x%02X" % ord(ch))
        lines.append("  {%d, %d, %d, %d, %d, %d},  // 0x%02X %s"
                     % (off, w, h, adv, xoff, yoff, ord(ch), safe))
    lines.append("};")
    lines.append("")
    # font
    lines.append("const GFXfont %s PROGMEM = {" % NAME)
    lines.append("  (uint8_t  *)%sBitmaps," % NAME)
    lines.append("  (GFXglyph *)%sGlyphs," % NAME)
    lines.append("  0x%02X, 0x%02X, %d };" % (FIRST, LAST, yadvance))
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    print("size=%dpx ascent=%d descent=%d yAdvance=%d bytes=%d"
          % (size, ascent, descent, yadvance, len(bitmaps)))
    print("sample 'SYDBNE' glyph width=%dpx  +arrow(%d)=%dpx"
          % (route_w("SYDBNE"), ARROW_BUDGET, route_w("SYDBNE") + ARROW_BUDGET))
    print("worst 'MWWMWW' width=%dpx  +arrow=%dpx"
          % (route_w("MWWMWW"), route_w("MWWMWW") + ARROW_BUDGET))
    print("wrote", OUT)

if __name__ == "__main__":
    main()
